In [5]:
import numpy as np

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X, y = np.arange(10).reshape((5,2)), range(5)

In [10]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
list(y)

[0, 1, 2, 3, 4]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [14]:
X_train

array([[8, 9],
       [0, 1],
       [6, 7]])

In [15]:
y_train

[4, 0, 3]

In [16]:
X_test

array([[2, 3],
       [4, 5]])

In [17]:
y_test

[1, 2]

In [18]:
# Linear Regression